name: work-log

dependencies:
  - base
  - warp
  - aeson
  - servant
  - servant-elm >= 0.6.0.2
  - elm-bridge >= 0.5.2
  - wai
  - servant-server
  - transformers
  - containers
  - monad-logger
  - string-conversions
  - persistent
  - persistent-template
  - persistent-postgresql
  - text
  - time
  - yaml

executables:
  server:
    main: Main.hs
    source-dirs:
      - server/src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - warp >= 3.2.3
      - hspec
      - servant-client
      - http-client
      - http-types
